name = "astro-mimascota"
compatibility_date = "2026-04-29"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"

[vars]
PUBLIC_API_URL = "https://action-safari-sit-queens.trycloudflare.com"
PUBLIC_WHATSAPP_NUMBER = "5493430000000"
